name: Minify Files
run-name: Minify ${{ github.run_number }} - ${{ github.sha }}
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  generate:
    name: Generate Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'master'
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Minify
        run: |
            npm install -g terser
            npm install -g csso-cli
            npm install -g html-minifier-terser
            shopt -s globstar
            shopt -s dotglob
            shopt -s extglob
            for i in **/*.js; do terser "$i" --compress -o "$i" || echo "BAD JS: $i"; done
            echo JS completed
            for i in **/*.css; do csso "$i" -o "$i" || echo "BAD CSS: $i"; done
            echo CSS completed
            if [ "${{ github.event_name }}" == "push" ]
            then
            GLOBIGNORE='HTML/**'
            fi
            for i in */**.html; do html-minifier-terser --collapse-boolean-attributes --collapse-whitespace --minify-css --minify-js --remove-comments --remove-empty-attributes --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --remove-tag-whitespace --use-short-doctype "$i" -o "$i" || echo "BAD HTML: $i"; done
            GLOBIGNORE=''
            echo HTML completed
      - name: Git Shenanigans
        run: |
            git add .
            git config user.email "KtaneContentMinifier@Timwi.de"
            git config user.name "Minifier"
            git commit -m "temp"
            git reset --mixed origin/minified
            git checkout -b minified origin/minified
            git add .
            git commit -m "Github Action: Auto Minified files - ${{ github.sha }}"
            git push --progress --force origin minified