name: Minify Files
run-name: Minify ${{ github.run_number }} - ${{ github.sha }}
on: push
jobs:
  generate:
    name: Generate Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Minify
        run: |
            npm install -g terser
            npm install -g csso-cli
            npm install -g html-minifier
            shopt -s globstar
            for i in **/*.js; do terser "$i" --compress -o "$i" || :; done
            echo JS completed
            for i in **/*.css; do csso "$i" -o "$i" || :; done
            echo CSS completed
            for i in **/*.html; do html-minifier --collapse-boolean-attributes --collapse-whitespace --minify-css --minify-js --remove-comments --remove-empty-attributes --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --remove-tag-whitespace --use-short-doctype "$i" -o "$i" || :; done
            echo HTML completed
      - name: Git Logging
        run: git add -n .
      - name: Auto commit minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "minified"
          create_branch: true
          commit_message: "Github Action: Auto Minified files"
          commit_user_name: Minifier
          commit_user_email: KtaneContentMinifier@Timwi.de
          commit_author: Minifier <KtaneContentMinifier@Timwi.de>