name: Minify Files
run-name: Minify ${{ github.run_number }} - ${{ github.sha }}
on:
  push:
    branches:
      - 'main'
    paths:
      - '**.js'
      - '**.css'
      - '**.html'
  workflow_dispatch:
jobs:
  generate:
    name: Generate Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Minify
        run: |
            # npm install -g terser
            # npm install -g csso-cli
            npm install -g html-minifier-terser
            shopt -s globstar
            shopt -s dotglob
            shopt -s extglob
            # for i in **/*.js; do terser "$i" --compress -o "$i" || echo "BAD JS: $i"; done
            # echo JS completed
            # for i in **/*.css; do csso "$i" -o "$i" || echo "BAD CSS: $i"; done
            # echo CSS completed
            for i in !(html/).html; do html-minifier-terser --collapse-boolean-attributes --collapse-whitespace --minify-css --minify-js --remove-comments --remove-empty-attributes --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --remove-tag-whitespace --use-short-doctype "$i" -o "$i" || echo "BAD HTML: $i"; done
            echo HTML completed
      - name: Git Shenanigans
        run: |
            git stash -u -a
            git checkout -b minified
            git pull origin/minified --no-rebase
            git stash pop
      - name: Auto commit minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: "minified"
          commit_message: "Github Action: Auto Minified files"
          commit_user_name: Minifier
          commit_user_email: KtaneContentMinifier@Timwi.de
          commit_author: Minifier <KtaneContentMinifier@Timwi.de>
          push_options: '--force'